@startuml
title Komponentendiagramm

interface IUserInteraction {
    + startButtonPressed()
    + stopButtonPressed()
}

interface ILogicControl {
    + startRadiation()
    + stopRadiation()
    + toggleRadiation()
}

interface ISystemAccess {
    + getTime()
    + playBeep(frequency, duration)
}

interface IUserInterface {
    + updateProgress(percent)
    + setLED(on)
    + logMessage(msg)
}


component "GUI-Komponente" as GUI {
    class RadiationUI
    class StatusLED
}

component "Steuerungslogik-Komponente" as Logic {
    class RadiationController
}

component "System-Komponente" as System {
    class SystemLayer
}


GUI -down-> Logic : nutzt >\nILogicControl
Logic -down-> System : nutzt >\nISystemAccess
Logic -up-> GUI : ruft auf >\nIUserInterface

' Schnittstellenbindungen
GUI ..> IUserInteraction
Logic ..> ILogicControl
Logic ..> IUserInterface
System ..> ISystemAccess

@enduml
